services:
  api:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
volumes:
  postgres_data:

networks:
  default:
    external:
      name: podman

